### ISSUE TITLE
findbugs dependency

### ISSUE THREAD

**Issue by NetAppBlueDevil** [OpenHFT/Koloboke#43]
While the findbugs jsr is needed to compile this project, it is not really a 'compile' scope dependency because it is not required to be present at runtime.  However compile scope causes it to be a transitive runtime dependency for users of this library and they need to actively exclude it.

The dependency in this project should be changed to 'provided' so that it is available when this project compiles but it does not transitively get included by projects using the library.

**Comment by leventov** [comment]
Thank you for a spot.
