### ISSUE TITLE
Invalid debugging symbols

### ISSUE THREAD

**Issue by botismarius** [OpenHFT/Koloboke#44]
I'm using koloboke version 0.6.7, jdk 8 version. I created a map with this codeL

map = HashObjObjMaps.newMutableMap();

While debugging the clear() method with Intellij IDEA (version 14.1.5, but i don't think it matters) the IDE shows the debugging cursor on the lines which actually contain comments or no code at all. Details: when I debug the MutableLHashParallelKVObjObjMapGO.clear() method:

    @Override
    public void clear() {
        int mc = modCount() + 1;
        super.clear();
        if (mc != modCount())
            throw new ConcurrentModificationException();
    }

the debugging works ok, however when I enter in modCount() method (inherited from MutableLHash) or in MutableLHash.clear() things look like in the attached screenshot
![koloboke_invalid_debugging_symbols](https://cloud.githubusercontent.com/assets/1162262/10394700/80352b5a-6ea1-11e5-9bb3-c0d0ee2b66d1.png)

**Comment by leventov** [comment]
After template processing, there are duplicate classes in IntelliJ's scope (It always highlights in red one of two), apparently when debugging, it chooses the template class to bind byte code to source (not the generated class), where line numbers are shifted.

I don't think you could do anything with this. In other collection lib's template systems, the templates are often not Java sources at all, while in Koloboke the templates are syntactically valid java sources -- this is already a huge step forward, allowing at least navigation in templates, using IntelliJ.

Koloboke debugging might be easier outside the Koloboke project itself -- you just add Koloboke as Gradle/Maven dependency, use "Attach sources" feature in IntelliJ, write a test, and step into Koloboke internals using debugger. Templates are not included into distributed JARs, so they shouldn't interfer.
